### ISSUE TITLE
'find' in collapsed headings 

### ISSUE THREAD

**Issue by ggrrll** [ipython-contrib/jupyter_contrib_nbextensions#1271]
Hi, 

first of all, thanks for the nice extension `Collapsible Headings`.

As far as I can see, the common browser-built-in 'find' cannot look  within a collapsed heather. 
Is there a way to make a collapsed section still 'searchable' by the browser ? 

Other solutions could be :

-   add a 'take me there' button in the _notebook-built-in_ 'find' (which still work also on collapsed sections)
- add 'un/collapse all' button, to quickly reopen/close all sections

Thanks for your contribution

ps: I use safari

**Comment by jcb91** [comment]
> first of all, thanks for the nice extension `Collapsible Headings`.

Thanks for kind words :smile: 

> As far as I can see, the common browser-built-in 'find' cannot look within a collapsed heather.
> Is there a way to make a collapsed section still 'searchable' by the browser ?

I think the browser excludes `display: none` elements from the find, so to get the browser's find working would require cells to be hidden in a different manner (e.g. width/height & overflow hidden). This would probably require alteration to the logic as well though, since I think we're using hidden/visible as a quick way to find next/previous cells. I'm not sure how easy it would be, but probably not impossible, unless it causes layout issues.

> Other solutions could be :
>
> * add a 'take me there' button in the notebook-built-in 'find' (which still work also on collapsed sections)

The lack of this feature has annoyed me before actually, it seems like the whole point of find in the first place :thinking:. Could be a nifty standalone extension (though really should go in core ultimately).

> * add 'un/collapse all' button, to quickly reopen/close all sections

This is pretty easy to add as an optional toolbar button, certainly

**Comment by jcb91** [comment]
> would require cells to be hidden in a different manner (e.g. width/height & overflow hidden)

This approach doesn't really work well. Although the browser can find the text, the user can't see it, and I don't think there's any way to catch events from it to handle revealing it.

**Comment by jcb91** [comment]
Also, it seems that I've already implemented an uncollapse-all action which has its own [configurable keybinding](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/7aa0192057c56a75b33f0f226b4485157b139bda/src/jupyter_contrib_nbextensions/nbextensions/collapsible_headings/collapsible_headings.yaml#L90-L93), and an [optional toggle-all toolbar button](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/7aa0192057c56a75b33f0f226b4485157b139bda/src/jupyter_contrib_nbextensions/nbextensions/collapsible_headings/collapsible_headings.yaml#L15-L18), which should work for uncollapsing everything (it un/collapses everything to match the first heading, so if that's already open, you might have to click twice). Hopefully these should help for now until the notebook's search can be patched

**Comment by ggrrll** [comment]
Thanks.

How do I activate it ? I couldn't find it in the shortcut list, after pressing H

**Comment by jcb91** [comment]
It should be active already by default (the [`use_shortcuts` setting](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/7aa0192057c56a75b33f0f226b4485157b139bda/src/jupyter_contrib_nbextensions/nbextensions/collapsible_headings/collapsible_headings.yaml#L70-L73) is true by default). It seems ok for me:

![screenshot from 2018-03-28 16-51-45](https://user-images.githubusercontent.com/5630710/38040981-8f148ee0-32a8-11e8-93fe-7b620d5c92ff.png)

**Comment by ggrrll** [comment]
it look a bit different in my case - please, see screenshot

ps: I am on `jupyter-contrib-nbextensions` v:  0.2.4

<img width="442" alt="screen shot 2018-03-28 at 18 55 10" src="https://user-images.githubusercontent.com/15370425/38044599-8d0a3b88-32ba-11e8-9737-1a8399039c77.png">

**Comment by jcb91** [comment]
> ps: I am on `jupyter-contrib-nbextensions` v: 0.2.4

Aha! The (un)collapse all actions & shortcuts were added in 0.3.0. I've just released 0.5.0 on pypi, conda-forge release to follow shortly.

**Comment by ggrrll** [comment]
Thanks. I am on 0.5.0 now, but that's still missing from my shortcuts... 🤔

( I use `jupyter-nbextensions-configurator` v 0.4.0 )

**Comment by jcb91** [comment]
Hmm, weird. Configurator version shouldn't matter, really.

Best guesses for possibilities are

1. You've possibly installed the 0.5.0 pip package, but not run the command to copy all the CSS & JavaScript (`jupyter contrib nbextensions install --sys-prefix`)
2. You have run that command, but you have the old & new installs in different jupyter path directories (e.g. one done with `--user`, the other with `--sys-prefix`). Run the notebook server with the `--debug` flag for more information about where the configurator finds each nbextension
3. Some confusion over virtual environments. This can happen if your notebook server runs in a different virtual environment (or conda environment) to the kernel. This is more likely if you're using jupyterhub, for example

**Comment by ggrrll** [comment]
Hi, 

thanks for your suggestions.
I had indeed forgotten to run the CSS & JS - I had to run it with `--user`  flag though, to have it work

Thanks again!

ps: so,  I guess I will close this issue for now, as we found a solution for this specific one, even tough the 'take me there' in the find button is really something missing -  is there an open issue/planned enhancement on that?
